export enum Message {
    SOMETHING_WENT_WRONG = "Something went wrong",
    NO_DATA_FOUND = "No data found",
    CREATE_FAILED = "Create failed",
    UPDATE_FAILED = "Update failed",
    DELETE_FAILED = "Delete failed",
    REMOVE_FAILED = "Remove failed", 
    UPLOAD_FAILED = "Upload failed", 
    BAD_REQUEST = "Bad Request",

    NO_MEMBER_NICK = "No member with that nickname!", 
    LOGIN_FAILED = "Login failed!", 
    BLOCKED_USER = "You have been blocked, contact restaurant", 
    USED_NICK_PHONE = "Nickname or phone number aready used!", 
    WRONG_PASSWORD = "Wrong password!", 
    NOT_AUTHENTICATED = "You are not authenticated, please login first",
    TOKEN_CREATION_FAILED = "Error! Token creation is failed", 
    TOKEN_NOT_EXIST = "Bearer Token is not provided", 
    ONLY_SPECIFIC_ROLES_ALLOWED = "Allowed only for members with spefic roles", 
    NOT_ALOWED_REQUEST = "Request is not allowed", 
    PROVIDE_ALLOWED_FORMAT = "Please provide jpg, jpeg or png images!", 
    SELF_SUBSCRIPTION_DENIED = "Self subscription is denied", 
}